//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HOADON
    {
        public int IDCTHD { get; set; }
        public int IDHoaDon { get; set; }
        public int IDMeNu { get; set; }
        public int SoLuong { get; set; }
        public double Gia { get; set; }
        public bool TinhTrang { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
