//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyQuanCafeEntities : DbContext
    {
        public QuanLyQuanCafeEntities()
            : base("name=QuanLyQuanCafeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAN> BAN { get; set; }
        public virtual DbSet<CT_HOADON> CT_HOADON { get; set; }
        public virtual DbSet<HOADON> HOADON { get; set; }
        public virtual DbSet<MENU> MENU { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIEN { get; set; }
        public virtual DbSet<NHOMMON> NHOMMON { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOAN { get; set; }
    
        public virtual int CapNhatIDbantrongHD(Nullable<int> idhd, Nullable<int> idban)
        {
            var idhdParameter = idhd.HasValue ?
                new ObjectParameter("idhd", idhd) :
                new ObjectParameter("idhd", typeof(int));
    
            var idbanParameter = idban.HasValue ?
                new ObjectParameter("idban", idban) :
                new ObjectParameter("idban", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatIDbantrongHD", idhdParameter, idbanParameter);
        }
    
        public virtual int CapNhatTongTien(Nullable<int> idban, Nullable<double> tamtinh)
        {
            var idbanParameter = idban.HasValue ?
                new ObjectParameter("idban", idban) :
                new ObjectParameter("idban", typeof(int));
    
            var tamtinhParameter = tamtinh.HasValue ?
                new ObjectParameter("tamtinh", tamtinh) :
                new ObjectParameter("tamtinh", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatTongTien", idbanParameter, tamtinhParameter);
        }
    
        public virtual int ChuyenTrangThai(Nullable<int> idban, string trangthai)
        {
            var idbanParameter = idban.HasValue ?
                new ObjectParameter("idban", idban) :
                new ObjectParameter("idban", typeof(int));
    
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChuyenTrangThai", idbanParameter, trangthaiParameter);
        }
    
        public virtual ObjectResult<DangNhap_Result> DangNhap(string taikhoan, string matkhau)
        {
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DangNhap_Result>("DangNhap", taikhoanParameter, matkhauParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> DoanhThu(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("DoanhThu", tungayParameter, denngayParameter);
        }
    
        public virtual int DoiMatKhau(string taikhoan, string matkhau)
        {
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DoiMatKhau", taikhoanParameter, matkhauParameter);
        }
    
        public virtual ObjectResult<DsBanTrong_Result> DsBanTrong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DsBanTrong_Result>("DsBanTrong");
        }
    
        public virtual ObjectResult<DSMonTheoNhom_Result> DSMonTheoNhom(Nullable<int> idnhom)
        {
            var idnhomParameter = idnhom.HasValue ?
                new ObjectParameter("idnhom", idnhom) :
                new ObjectParameter("idnhom", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSMonTheoNhom_Result>("DSMonTheoNhom", idnhomParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> HDCThanhToan(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("HDCThanhToan", tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> HDDThanhToan(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("HDDThanhToan", tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<HDTungBan_Result> HDTungBan(Nullable<int> idban)
        {
            var idbanParameter = idban.HasValue ?
                new ObjectParameter("idban", idban) :
                new ObjectParameter("idban", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HDTungBan_Result>("HDTungBan", idbanParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> IDHoaDon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("IDHoaDon");
        }
    
        public virtual ObjectResult<Nullable<int>> IDNhom(string tennhom)
        {
            var tennhomParameter = tennhom != null ?
                new ObjectParameter("tennhom", tennhom) :
                new ObjectParameter("tennhom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("IDNhom", tennhomParameter);
        }
    
        public virtual ObjectResult<KiemTraCmnd_Result> KiemTraCmnd(string cmnd)
        {
            var cmndParameter = cmnd != null ?
                new ObjectParameter("cmnd", cmnd) :
                new ObjectParameter("cmnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KiemTraCmnd_Result>("KiemTraCmnd", cmndParameter);
        }
    
        public virtual ObjectResult<KiemTraQuyen_Result> KiemTraQuyen(string taikhoan, Nullable<int> quyen)
        {
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            var quyenParameter = quyen.HasValue ?
                new ObjectParameter("quyen", quyen) :
                new ObjectParameter("quyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KiemTraQuyen_Result>("KiemTraQuyen", taikhoanParameter, quyenParameter);
        }
    
        public virtual ObjectResult<KiemTraTrungLap_Result> KiemTraTrungLap(string taikhoan)
        {
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KiemTraTrungLap_Result>("KiemTraTrungLap", taikhoanParameter);
        }
    
        public virtual ObjectResult<KTDoiMatKhau_Result> KTDoiMatKhau(string taikhoan, string matkhau)
        {
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KTDoiMatKhau_Result>("KTDoiMatKhau", taikhoanParameter, matkhauParameter);
        }
    
        public virtual ObjectResult<KTHoaDon_Result> KTHoaDon(Nullable<int> idban)
        {
            var idbanParameter = idban.HasValue ?
                new ObjectParameter("idban", idban) :
                new ObjectParameter("idban", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KTHoaDon_Result>("KTHoaDon", idbanParameter);
        }
    
        public virtual ObjectResult<KTNhomMon_Result> KTNhomMon(string tennhom)
        {
            var tennhomParameter = tennhom != null ?
                new ObjectParameter("tennhom", tennhom) :
                new ObjectParameter("tennhom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KTNhomMon_Result>("KTNhomMon", tennhomParameter);
        }
    
        public virtual ObjectResult<KTTrungLapMon_Result> KTTrungLapMon(string tenmon)
        {
            var tenmonParameter = tenmon != null ?
                new ObjectParameter("tenmon", tenmon) :
                new ObjectParameter("tenmon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KTTrungLapMon_Result>("KTTrungLapMon", tenmonParameter);
        }
    
        public virtual ObjectResult<LayDanhSachBan_Result> LayDanhSachBan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDanhSachBan_Result>("LayDanhSachBan");
        }
    
        public virtual ObjectResult<LaydanhsachCT_HD_Result> LaydanhsachCT_HD(Nullable<int> idhd)
        {
            var idhdParameter = idhd.HasValue ?
                new ObjectParameter("idhd", idhd) :
                new ObjectParameter("idhd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LaydanhsachCT_HD_Result>("LaydanhsachCT_HD", idhdParameter);
        }
    
        public virtual ObjectResult<LayDanhSachHD_Result> LayDanhSachHD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDanhSachHD_Result>("LayDanhSachHD");
        }
    
        public virtual ObjectResult<LayDanhSachMenu_Result> LayDanhSachMenu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDanhSachMenu_Result>("LayDanhSachMenu");
        }
    
        public virtual ObjectResult<LayDanhSachNhomMon_Result> LayDanhSachNhomMon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDanhSachNhomMon_Result>("LayDanhSachNhomMon");
        }
    
        public virtual ObjectResult<LayDanhSachNV_Result> LayDanhSachNV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDanhSachNV_Result>("LayDanhSachNV");
        }
    
        public virtual ObjectResult<LayDanhSachTK_Result> LayDanhSachTK()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDanhSachTK_Result>("LayDanhSachTK");
        }
    
        public virtual ObjectResult<LayThongTinMon_Result> LayThongTinMon(Nullable<int> idmenu)
        {
            var idmenuParameter = idmenu.HasValue ?
                new ObjectParameter("idmenu", idmenu) :
                new ObjectParameter("idmenu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayThongTinMon_Result>("LayThongTinMon", idmenuParameter);
        }
    
        public virtual ObjectResult<LayThongTinTheoBan_Result> LayThongTinTheoBan(Nullable<int> idban)
        {
            var idbanParameter = idban.HasValue ?
                new ObjectParameter("idban", idban) :
                new ObjectParameter("idban", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayThongTinTheoBan_Result>("LayThongTinTheoBan", idbanParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int SuaMon(Nullable<int> idmon, string tenmon, Nullable<int> idnhom, string donvitinh, Nullable<double> gia)
        {
            var idmonParameter = idmon.HasValue ?
                new ObjectParameter("idmon", idmon) :
                new ObjectParameter("idmon", typeof(int));
    
            var tenmonParameter = tenmon != null ?
                new ObjectParameter("tenmon", tenmon) :
                new ObjectParameter("tenmon", typeof(string));
    
            var idnhomParameter = idnhom.HasValue ?
                new ObjectParameter("idnhom", idnhom) :
                new ObjectParameter("idnhom", typeof(int));
    
            var donvitinhParameter = donvitinh != null ?
                new ObjectParameter("donvitinh", donvitinh) :
                new ObjectParameter("donvitinh", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("gia", gia) :
                new ObjectParameter("gia", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaMon", idmonParameter, tenmonParameter, idnhomParameter, donvitinhParameter, giaParameter);
        }
    
        public virtual int SuaNhomMon(Nullable<int> idnhom, string tennhom)
        {
            var idnhomParameter = idnhom.HasValue ?
                new ObjectParameter("idnhom", idnhom) :
                new ObjectParameter("idnhom", typeof(int));
    
            var tennhomParameter = tennhom != null ?
                new ObjectParameter("tennhom", tennhom) :
                new ObjectParameter("tennhom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaNhomMon", idnhomParameter, tennhomParameter);
        }
    
        public virtual int SuaNV(Nullable<int> idnhanvien, string hovaten, string gioitinh, Nullable<System.DateTime> ngaysinh, string diachi, string sdt, string cmnd)
        {
            var idnhanvienParameter = idnhanvien.HasValue ?
                new ObjectParameter("idnhanvien", idnhanvien) :
                new ObjectParameter("idnhanvien", typeof(int));
    
            var hovatenParameter = hovaten != null ?
                new ObjectParameter("hovaten", hovaten) :
                new ObjectParameter("hovaten", typeof(string));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var cmndParameter = cmnd != null ?
                new ObjectParameter("cmnd", cmnd) :
                new ObjectParameter("cmnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaNV", idnhanvienParameter, hovatenParameter, gioitinhParameter, ngaysinhParameter, diachiParameter, sdtParameter, cmndParameter);
        }
    
        public virtual int TangBan(string tenban)
        {
            var tenbanParameter = tenban != null ?
                new ObjectParameter("tenban", tenban) :
                new ObjectParameter("tenban", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TangBan", tenbanParameter);
        }
    
        public virtual ObjectResult<string> TenNhom(Nullable<int> idnhom)
        {
            var idnhomParameter = idnhom.HasValue ?
                new ObjectParameter("idnhom", idnhom) :
                new ObjectParameter("idnhom", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("TenNhom", idnhomParameter);
        }
    
        public virtual int ThanhToanHD(Nullable<int> idhd)
        {
            var idhdParameter = idhd.HasValue ?
                new ObjectParameter("idhd", idhd) :
                new ObjectParameter("idhd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThanhToanHD", idhdParameter);
        }
    
        public virtual int ThemCTHD(Nullable<int> idhoadon, Nullable<int> idmenu, Nullable<int> soluong, Nullable<double> gia)
        {
            var idhoadonParameter = idhoadon.HasValue ?
                new ObjectParameter("idhoadon", idhoadon) :
                new ObjectParameter("idhoadon", typeof(int));
    
            var idmenuParameter = idmenu.HasValue ?
                new ObjectParameter("idmenu", idmenu) :
                new ObjectParameter("idmenu", typeof(int));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("gia", gia) :
                new ObjectParameter("gia", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemCTHD", idhoadonParameter, idmenuParameter, soluongParameter, giaParameter);
        }
    
        public virtual int ThemHoaDon(Nullable<int> idban, Nullable<int> idnv, Nullable<double> tamtinh)
        {
            var idbanParameter = idban.HasValue ?
                new ObjectParameter("idban", idban) :
                new ObjectParameter("idban", typeof(int));
    
            var idnvParameter = idnv.HasValue ?
                new ObjectParameter("idnv", idnv) :
                new ObjectParameter("idnv", typeof(int));
    
            var tamtinhParameter = tamtinh.HasValue ?
                new ObjectParameter("tamtinh", tamtinh) :
                new ObjectParameter("tamtinh", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemHoaDon", idbanParameter, idnvParameter, tamtinhParameter);
        }
    
        public virtual int ThemMon(string tenmon, Nullable<int> idnhom, string donvitinh, Nullable<double> gia)
        {
            var tenmonParameter = tenmon != null ?
                new ObjectParameter("tenmon", tenmon) :
                new ObjectParameter("tenmon", typeof(string));
    
            var idnhomParameter = idnhom.HasValue ?
                new ObjectParameter("idnhom", idnhom) :
                new ObjectParameter("idnhom", typeof(int));
    
            var donvitinhParameter = donvitinh != null ?
                new ObjectParameter("donvitinh", donvitinh) :
                new ObjectParameter("donvitinh", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("gia", gia) :
                new ObjectParameter("gia", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemMon", tenmonParameter, idnhomParameter, donvitinhParameter, giaParameter);
        }
    
        public virtual int ThemNhomMon(string tennhom)
        {
            var tennhomParameter = tennhom != null ?
                new ObjectParameter("tennhom", tennhom) :
                new ObjectParameter("tennhom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemNhomMon", tennhomParameter);
        }
    
        public virtual int ThemNV(string hovaten, string gioitinh, string diachi, string sdt, string cmnd, Nullable<System.DateTime> ngaysinh)
        {
            var hovatenParameter = hovaten != null ?
                new ObjectParameter("hovaten", hovaten) :
                new ObjectParameter("hovaten", typeof(string));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var cmndParameter = cmnd != null ?
                new ObjectParameter("cmnd", cmnd) :
                new ObjectParameter("cmnd", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemNV", hovatenParameter, gioitinhParameter, diachiParameter, sdtParameter, cmndParameter, ngaysinhParameter);
        }
    
        public virtual int ThemTK(Nullable<int> idnv, string taikhoan, string matkhau, Nullable<bool> phanquyen)
        {
            var idnvParameter = idnv.HasValue ?
                new ObjectParameter("idnv", idnv) :
                new ObjectParameter("idnv", typeof(int));
    
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var phanquyenParameter = phanquyen.HasValue ?
                new ObjectParameter("phanquyen", phanquyen) :
                new ObjectParameter("phanquyen", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemTK", idnvParameter, taikhoanParameter, matkhauParameter, phanquyenParameter);
        }
    
        public virtual ObjectResult<ThongKe_Result> ThongKe(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKe_Result>("ThongKe", tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<TimKiemHDTheoNgay_Result> TimKiemHDTheoNgay(Nullable<System.DateTime> ngay)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimKiemHDTheoNgay_Result>("TimKiemHDTheoNgay", ngayParameter);
        }
    
        public virtual int XoaBan(Nullable<int> idban)
        {
            var idbanParameter = idban.HasValue ?
                new ObjectParameter("idban", idban) :
                new ObjectParameter("idban", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaBan", idbanParameter);
        }
    
        public virtual int XoaMon(Nullable<int> idmon)
        {
            var idmonParameter = idmon.HasValue ?
                new ObjectParameter("idmon", idmon) :
                new ObjectParameter("idmon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaMon", idmonParameter);
        }
    
        public virtual int XoaNhomMon(Nullable<int> idnhom)
        {
            var idnhomParameter = idnhom.HasValue ?
                new ObjectParameter("idnhom", idnhom) :
                new ObjectParameter("idnhom", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaNhomMon", idnhomParameter);
        }
    
        public virtual int XoaNV(Nullable<int> idnhanvien)
        {
            var idnhanvienParameter = idnhanvien.HasValue ?
                new ObjectParameter("idnhanvien", idnhanvien) :
                new ObjectParameter("idnhanvien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaNV", idnhanvienParameter);
        }
    
        public virtual int XoaTK(string taikhoan)
        {
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaTK", taikhoanParameter);
        }
    
        public virtual ObjectResult<HDThanhToan_Result> HDThanhToan(Nullable<int> idhd)
        {
            var idhdParameter = idhd.HasValue ?
                new ObjectParameter("idhd", idhd) :
                new ObjectParameter("idhd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HDThanhToan_Result>("HDThanhToan", idhdParameter);
        }
    
        public virtual ObjectResult<KTTenban_Result> KTTenban(string tenban)
        {
            var tenbanParameter = tenban != null ?
                new ObjectParameter("tenban", tenban) :
                new ObjectParameter("tenban", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KTTenban_Result>("KTTenban", tenbanParameter);
        }
    
        public virtual ObjectResult<NguoiDungTK_Result> NguoiDungTK(string taikhoan)
        {
            var taikhoanParameter = taikhoan != null ?
                new ObjectParameter("taikhoan", taikhoan) :
                new ObjectParameter("taikhoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NguoiDungTK_Result>("NguoiDungTK", taikhoanParameter);
        }
    
        public virtual ObjectResult<KTTaiKhoanNV_Result> KTTaiKhoanNV(Nullable<int> idnv)
        {
            var idnvParameter = idnv.HasValue ?
                new ObjectParameter("idnv", idnv) :
                new ObjectParameter("idnv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KTTaiKhoanNV_Result>("KTTaiKhoanNV", idnvParameter);
        }
    
        public virtual ObjectResult<TaiKhoanNV_Result> TaiKhoanNV(Nullable<int> idnv)
        {
            var idnvParameter = idnv.HasValue ?
                new ObjectParameter("idnv", idnv) :
                new ObjectParameter("idnv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TaiKhoanNV_Result>("TaiKhoanNV", idnvParameter);
        }
    
        public virtual ObjectResult<DSNVChuacoTK_Result> DSNVChuacoTK()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DSNVChuacoTK_Result>("DSNVChuacoTK");
        }
    
        public virtual ObjectResult<LayHDThanhToan_Result> LayHDThanhToan(Nullable<int> idhd)
        {
            var idhdParameter = idhd.HasValue ?
                new ObjectParameter("idhd", idhd) :
                new ObjectParameter("idhd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayHDThanhToan_Result>("LayHDThanhToan", idhdParameter);
        }
    
        public virtual int TachCT_HD(Nullable<int> idhdmoi, Nullable<int> idhdcu, Nullable<int> idmenu)
        {
            var idhdmoiParameter = idhdmoi.HasValue ?
                new ObjectParameter("idhdmoi", idhdmoi) :
                new ObjectParameter("idhdmoi", typeof(int));
    
            var idhdcuParameter = idhdcu.HasValue ?
                new ObjectParameter("idhdcu", idhdcu) :
                new ObjectParameter("idhdcu", typeof(int));
    
            var idmenuParameter = idmenu.HasValue ?
                new ObjectParameter("idmenu", idmenu) :
                new ObjectParameter("idmenu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TachCT_HD", idhdmoiParameter, idhdcuParameter, idmenuParameter);
        }
    
        public virtual int TongTienSauTach(Nullable<int> idban, Nullable<double> tongtienmoi)
        {
            var idbanParameter = idban.HasValue ?
                new ObjectParameter("idban", idban) :
                new ObjectParameter("idban", typeof(int));
    
            var tongtienmoiParameter = tongtienmoi.HasValue ?
                new ObjectParameter("tongtienmoi", tongtienmoi) :
                new ObjectParameter("tongtienmoi", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TongTienSauTach", idbanParameter, tongtienmoiParameter);
        }
    }
}
